### ISSUE TITLE
Using other Cellpose 2.0 built-in models ?

### ISSUE THREAD

**Issue by ofrag** [BIOP/qupath-extension-cellpose#19]
Hi,

Thanks for the great Cellpose extension !
I have data for which other built-in Cellpose models work better than cyto2 (tissuenet, TN1, TN2, TN3) 
I wonder if you can add an option to use all the models built-in cellpose 2.0.

Thanks
Ofra

**Comment by lacan** [comment]
Hi Ofra, as far as I know, all models are available, the examples given are not complete. If it has a string that you can use from the command line of cellpose, then you can call it from the QuPath extension. 

Do you have an example of when it does not work?

Oli

**Comment by lacan** [comment]
Closing this from lack of activity
