### ISSUE TITLE
bash no permission

### ISSUE THREAD

**Issue by mcib3d** [BIOP/qupath-extension-cellpose#20]
Hi,

I tried to run the prediction extension script on Linux, but I get this error : 
```
bash -c "/home/thomas/App/miniconda3/envs/cellpose/bin/python3.8 -W ignore -m cellpose --dir /home/thomas/App/QuPath/projects/omero/cellpose-temp --pretrained_model cyto2 --no_norm --save_tif --no_npy --use_gpu --verbose"
INFO: This command should run directly if copy-pasted into your shell
ERROR: Failed to Run Cellpose
java.io.IOException: Cannot run program "bash": error=13, Permission non accordée
```
The command line works fine and bash has standard permission (x for all).

Thanks.

**Comment by NicoKiaru** [comment]
There seems to be a weird issue with linux and permissions from Java.

Here are two linked issues on the forum:

https://forum.image.sc/t/cellpose-in-qupath-qupath-extension-cellpose/58901/40

https://forum.image.sc/t/could-not-execute-system-command-in-qupath-thanks-to-groovy-script-and-java-processbuilder-class/61629

I'm afraid the only known solution is to build from source...

ping @lacan

**Comment by lacan** [comment]
Considering this closed as we got no reply
