### ISSUE TITLE
Preprocessing options

### ISSUE THREAD

**Issue by pakiessling** [BIOP/qupath-extension-cellpose#23]
Super nice tool, very helpful!

The results are actually nicer than what I get from the cellpose CLI.
I think it is the preprocessing steps       `.preprocess( ImageOps.Filters.median(1) ) .normalizePercentilesGlobal(0.1, 99.8, 10)`
Could you by any chance point me to the closest scikit-image or cv2 equivalent?

Thank you so much

**Comment by lacan** [comment]
Hi @pakiessling, 

Unfortunately I do not have the scikit-image or cv2 equivalents. Best

Oli
