### ISSUE TITLE
Further training on an image? 

### ISSUE THREAD

**Issue by penguingiraffe2** [BIOP/qupath-extension-cellpose#26]
How can I train a classifier on more than one image? 
Can I just reference the model that I initially made from running the training script on the first image on the next image? 

Will it build on the model or just rewrite it ? Thanks!

**Comment by lacan** [comment]
The training script will go through all the annotated rectangles all the images in the QuPath project, not just one. 

Training is done on all images, and there is no "further training" in that aspect. You should prepare all images first then run the training script. You should see in the log that it is going through all entries in your project
