### ISSUE TITLE
"WARN: Unable to write image" when running Cellpose_training_template.groovy

### ISSUE THREAD

**Issue by tvanluu07** [BIOP/qupath-extension-cellpose#30]
When I run the training template (Cellpose_training_template.groovy) I get the follow error message:

```
INFO: Neither diameter nor overlap provided. Overlap defaulting to 60 pixels. Use `.setOverlap( int )` to modify overlap
INFO: If tiling is necessary, 60 pixels overlap will be taken between tiles
INFO: Found 4 Training objects and 2 Validation objects in image 2023_07_27_CV__01.czi - Scene #1
WARN: Unable to write image
ERROR: Unable to write /Volumes/Cresyl_Violet/Cresyl_Violet_trial3_2183_3069/Project/cellpose-training/train/2023_07_27_CV__01.czi - Scene #1_region_0.tif!  No compatible writer found.
```
The script then later fails as it was unable to find the images in the training directory since they were never written. 

On a potentially related note I don't see Cellpose in the "Extensions" dropdown but I do see it in the installed extensions dir.

QuPath System Info:
Version: 0.4.3
Java version: 17.0.6
Operating system:	Mac OS X  -  13.4.1

**Comment by tvanluu07** [comment]
Originally ran v0.6 but after updating to v0.8 still hitting same issue.

**Comment by lacan** [comment]
Dear @tvanluu07, 
thanks for the feeback. When you say it worked in v0.6 but not anymore, did you try to run v0.8 on a dataset that you knew worked before?

So far we experienced the `No compatible writer found.` issue in the following cases
1. The channel names were incorrect in the builder, so the image writer could not find the requested channels
2. The rectangles were too close or beyond the edges of the image, so there were no pixels to export
3. There were special characters in the file name, which caused it to fail. 

In case you believe that none of these apply to you, I would need to see a minimal example project alors with the export script that you are using.

> On a potentially related note I don't see Cellpose in the "Extensions" dropdown but I do see it in the installed extensions dir.
Please make sure that you deleted the older extension from your `extensions` directory. What does `Extensions > Installed Extensions` say?

**Comment by tvanluu07** [comment]
@Iacan 
Sorry I meant I originally tried running v0.6 but that one did not work either. When I updated to v0.8 I do now see the Cellpose Extension in the dropdown. I deleted the old .jar & .py files and replaced them with the new ones to update.

Thanks for the guidance! It was an issue with the channel names. The script is now able to write the files.

I'm now hitting a new issue with the cellpose command the extension is generating:
```
INFO: Executing command:
bash -c " -W ignore -m cellpose --train --dir /Volumes/Thuyvan_5TB/Thuyvan/Cresyl_Violet/Cresyl_Violet_trial3_2183_3069/Project/cellpose-training/train --test_dir /Volumes/Thuyvan_5TB/Thuyvan/Cresyl_Violet/Cresyl_Violet_trial3_2183_3069/Project/cellpose-training/test --pretrained_model cyto --use_gpu --verbose"
INFO: This command should run directly if copy-pasted into your shell
INFO: Virtual Environment Runner Finished
INFO: Cellpose2D: bash: -W: command not found
ERROR: Runner 'Cellpose2D' exited with value 127. Please check output above for indications of the problem.
INFO: Cellpose command finished running
ERROR: null in Cellpose_training_template_edit.groovy at line number 35
```

Notably when I run this cellpose command via the command line without the "-W ignore -m" it seems to work. Any idea why this might be happening or how I can run the extension without those args?

**Comment by lacan** [comment]
With no news from you, I will assume that the suggestions worked. 
Closing this for now
