### ISSUE TITLE
Make paths space safe

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/qupath-extension-cellpose#34]
As I'm sorting some old emails, I found this issue:

https://forum.image.sc/t/cellpose-qupath-extension-problem/82176/3

And I'm still unsure whether the 'space' issue in the extension has been solved. So, here's an issue just in case we forget it.

**Comment by yau-lim** [comment]
Hi @lacan , as of v0.9.2, I am still having issues with using Cellpose when there are spaces in the Python path name when set in QuPath's preference menu.

In my case, my `Cellpose 'python.exe location` is set to `C:\Users\ASAP Image Analysis\anaconda3\envs\cellpose\python.exe`.

When I run Cellpose, I get this error in the log:
```
INFO: Executing command:
cmd.exe /C "C:\Users\ASAP Image Analysis\anaconda3\envs\cellpose\python.exe" -W ignore -m cellpose --dir "path\to\\qupathproj\cellpose-temp" --pretrained_model cyto3 --diameter 0.0 --no_norm --save_tif --no_npy --use_gpu --verbose
INFO: This command should run directly if copy-pasted into your shell
INFO: Virtual Environment Runner Started
INFO: Cellpose2D: 'C:\Users\ASAP' is not recognized as an internal or external command,
```

and of course it fails to complete the run.

I tried various ways to escape the spaces, including surrounding the path with quotes `"`, escaping with `\`, and `^`, but they all failed to work.

Do you have any other suggestions I can try to resolve this?

Many thanks in advance.
