### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by apal6** [BIOP/qupath-extension-cellpose#36]
Hi,

I downloaded the latest cellpose version, dragged and dropped it in QuPath main window but I still can't find it through Edit> Preferences > Cellpose. Any suggestions? 
Thank you in advance!

**Comment by lacan** [comment]
Did you unzip the file before dragging and dropping it?

**Comment by apal6** [comment]
Yes, I did. That's how I added Stardist to my extensions.

**Comment by psobolewskiPhD** [comment]
What version of QuPath are you using?
And can you clarify exactly the issue?
You don't see this QuPath extension in the Preferences? or you can't find your cellpose installation?
Have you tried restarting QuPath? Do you see the extension in your extensions directory that is in QuPath Preferences?

**Comment by apal6** [comment]
Thank you for you reply. I just re-installed everything. I am using 0.5.0 version of QuPath and cellpose version 0.9.0. However, I am not sure how to locate these URLs from the cellpose conda env. 
<img width="515" alt="Screenshot 2023-12-22 at 11 30 05 AM" src="https://github.com/BIOP/qupath-extension-cellpose/assets/127814354/094bdd7f-55a5-4ada-bc15-c882456ef9c3">
<img width="572" alt="Screenshot 2023-12-22 at 11 32 20 AM" src="https://github.com/BIOP/qupath-extension-cellpose/assets/127814354/8e58aa7a-9229-42b2-a32a-d482c12eace9">

I dragged and dropped the cellpose in QuPath and also created a conda env. 
What do you think is going wrong? Really appreciate your time.

Thank you!

**Comment by psobolewskiPhD** [comment]
You need to actually install cellpose into a Python virtual environment and then get the proper path. see:
https://github.com/BIOP/qupath-extension-cellpose#installation-from-the-official-cellpose-documentation

**Comment by apal6** [comment]
Sure, this is how I did: 

From the terminal, 

conda
conda create --name cellpose python=3.8 anaconda
conda activate cellpose
python -m pip install cellpose
python -m pip install 'cellpose[gui]'
python -m pip install omnipose scikit-image`

**Comment by psobolewskiPhD** [comment]
In that environment (so after `conda activate cellpose`)
type `which python`
It should give you something like:
`{HOME}/conda/envs/cellpose/bin/python`
Copy-paste that into the QuPath Preference cellpose section.

**Comment by apal6** [comment]
Thank you, I was able to put the URL in QuPath and run cellpose from the command line. Gui is pretty straightforward, i will play with it a bit. 
Just to make sure that everything is all set and I should be able to run the cell segmentation scripts in QuPath now?

**Comment by psobolewskiPhD** [comment]
if you can use cellpose from the command line and have told QuPAth where you python with cellpose is, then yes, the scripts should work. I recommend reading the README and the comments in the scripts carefully!

**Comment by apal6** [comment]
Thank you @psobolewskiPhD for you time and help.
