### ISSUE TITLE
channels name can not contain space 

### ISSUE THREAD

**Issue by romainGuiet** [BIOP/qupath-extension-cellpose#38]
Tried to use the script to export Training/Validation images, get the error : 

```
WARN: Unable to write image
ERROR: Unable to write XXX !  No compatible writer found.
ERROR: Troubleshooting:
 - Check that the channel names are correct in the builder.
 
```
if the channel name is `Channel 4` but it works as soon as you remove the space or replace with `-`, like `Channel-4`

**Comment by lacan** [comment]
I have been unable to fix this yet. I will see if it is the same with the StarDist extension, and if it is not, I will see what they do differently in their code

**Comment by lacan** [comment]
I have tested this again on both Cellpose and StarDist with the image LuCa7 and changing the DAPI channel to "The Nuclei 4" and both extensions are running the cell detection.
Please open this again in case there is still an issue
