### ISSUE TITLE
can not export upscaled image

### ISSUE THREAD

**Issue by romainGuiet** [BIOP/qupath-extension-cellpose#39]
- images are Fiji exported tifs
- image pixel size is 0.09 micron

With the script : 
```
def pixelSize = 0.09
def cellpose = Cellpose2D.builder( "None" )
                .pixelSize(pixelSize)
                .channels( "Channel-4" )    
                .build()
```
it works but if `pixelSize = 0.045` (or smaller, 0.04 ... ) get the error : 

```
WARN: Unable to write image
ERROR: Unable to write XXX  No compatible writer found.
ERROR: Troubleshooting:
 - Check that the channel names are correct in the builder.
```

_Surprisingly_ , with `pixelSize = 0.05`, the image is exported but with a pixel size of  `0.09` !

**Comment by lacan** [comment]
the downsampling is taken as an int, this is why there is an issue. 

QuPath actually allows a double for the downsample so it is possible, I will add a check for this to allow fractions.

**Comment by lacan** [comment]
Fixed in latest release
