### ISSUE TITLE
Specify intensity measurements in CellposeBuilder

### ISSUE THREAD

**Issue by RouvenHoefflin** [BIOP/qupath-extension-cellpose#49]
Hi,

Thanks a lot for that amazing plugin!
I’m using the cellpose extension (v0.9) in QuPath (v0.5.1) to run nucelar segmentation on very large super high-plex immunofluorescence images (>70plex).
To reduce the number of measurments, I want to specify the intensity measurments for the segmented cell compartments using the cellpose builder as described here (and not measure everything using the default code: “measureIntensity()”:

[biop.github.io](https://biop.github.io/qupath-extension-cellpose/qupath/ext/biop/cellpose/CellposeBuilder.html)
[CellposeBuilder (qupath-extension-cellpose 0.9.3 API)](https://biop.github.io/qupath-extension-cellpose/qupath/ext/biop/cellpose/CellposeBuilder.html)
declaration: package: qupath.ext.biop.cellpose, class: CellposeBuilder

However, I don’t fully understand the syntax and couldn’t find examples online.
Could you provide a line of code as example, in which the specified following intensity features get measured:

Compartments: Nucleus, Cytoplasm (exclude e.g. Membrane, Cell etc.)
Markers/channels: DAPI, CD45 (exclude all others)
Stats: Mean, Median, Max (exclude e.g. Min, STDV etc.)
This will help to reduce the data burden by a lot, which is importent for downstream analysis.

Thanks a lot for your help.

Rouven

**Comment by lacan** [comment]
Hi, We've discussed the issue in the forum here
https://forum.image.sc/t/specify-intensity-measurements-for-cellpose-extension-in-qupath/99814/2?u=oburri
So I am closing this ticket :)
