### ISSUE TITLE
Tiled Segmentation

### ISSUE THREAD

**Issue by Jooppie** [BIOP/qupath-extension-cellpose#5]
Hi,

![image](https://user-images.githubusercontent.com/46439648/152366810-b0778673-611f-486b-90c1-9f15106f77a4.png)

I tested training a network. Works OK I think. It is really fast, so I hope it used my complete training patches etc. However using the trained network gives a problem if the images are big and the script runs prediction on tiles. See picture. I also tried training Stardist, and predicting with Stardist does not give these effects at the borders. 

Best, Ron

**Comment by lacan** [comment]
Hi @Jooppie 
We use an overlap that is a multiple of the diameter that is provided by the cellpose builder. That overlap should be bigger than the largest object that you have. You can try to overcome the automatic overlap calculation by trying the following just before the detection.
The fact that it's not working is probably because you are using a custom model without setting the `diameter`

```
import qupath.ext.biop.cellpose.Cellpose2D

// Specify the model name (cyto, nuc, cyto2, omni_bact or a path to your custom model)
def pathModel = 'cyto'

def cellpose = Cellpose2D.builder( pathModel )
        .pixelSize( 0.5 )              // Resolution for detection
        .channels( 'DAPI' )            // Select detection channel(s)
//        .preprocess( ImageOps.Filters.median(1) )                // List of preprocessing ImageOps to run on the images before exporting them
//        .tileSize(2048)                // If your GPU can take it, make larger tiles to process fewer of them. Useful for Omnipose
//        .cellposeChannels(1,2)         // Overwrites the logic of this plugin with these two values. These will be sent directly to --chan and --chan2
//        .maskThreshold(-0.2)           // Threshold for the mask detection, defaults to 0.0
//        .flowThreshold(0.5)            // Threshold for the flows, defaults to 0.4 
//        .diameter(0)                   // Median object diameter. Set to 0.0 for the `bact_omni` model or for automatic computation
//        .invert()                      // Have cellpose invert the image
//        .useOmnipose()                 // Add the --omni flag to use the omnipose segmentation model
//        .excludeEdges()                // Clears objects toutching the edge of the image (Not of the QuPath ROI)
//        .clusterDBSCAN()               // Use DBSCAN clustering to avoir over-segmenting long object
        .cellExpansion(5.0)            // Approximate cells based upon nucleus expansion
//        .cellConstrainScale(1.5)       // Constrain cell expansion using nucleus size
//        .classify("My Detections")     // PathClass to give newly created objects
        .measureShape()                // Add shape measurements
        .measureIntensity()            // Add cell measurements (in all compartments)  
//        .createAnnotations()           // Make annotations instead of detections. This ignores cellExpansion
        .build()

// Run detection for the selected objects
def imageData = getCurrentImageData()
def pathObjects = getSelectedObjects()
if (pathObjects.isEmpty()) {
    Dialogs.showErrorMessage("Cellpose", "Please select a parent object!")
    return
}

cellpose.overlap = 200 // in pixels : amount of overlap between tiles. Should be larger than the largest object.

cellpose.detectObjects(imageData, pathObjects)
println 'Done!'
```

**Comment by Jooppie** [comment]
Hi

Thanks for that, it works! It also works if I include .diameter(130)  while
training and predicting.

Some remarks.

In training: I see:
INFO: Cellpose2D-train: >>>> !NEW LOGGING SETUP! To see cellpose progress,
set --verbose
INFO: Cellpose2D-train: No --verbose => no progress or info printed

So no progress is shown.

Also the imageJ table and graph show up empty in my case.

Furthermore: I added;
                .useGPU()
                .build()

For the training code: on the github website the .build() is not in the
example
Also on the website you show the "simplest way so far", but that is even
simpler on windows, you only need the conda environment. (with cuda if
possible, and use the .useGPU())

Some enhancements (if possible)

Use the calculated H & E channel for training and prediction (or is this
already possible?).

Thanks for the help and nice plugin!

Best. Ron




Op do 3 feb. 2022 om 17:15 schreef Olivier Burri ***@***.***>:

**Comment by lacan** [comment]
Dear Ron, 

For help on how to use this extension, please refer to the Image.sc forum and place a post there
https://forum.image.sc/t/cellpose-in-qupath-qupath-extension-cellpose/58901/74

Regarding the training not displaying anything. This Commit fixes it: https://github.com/BIOP/qupath-extension-cellpose/commit/d16b539cce6787dda02ad00127498dcc5807ca0c

A new release has been made.
